spring:
  application:
    name: compra-service
server:
  port: 8087
eureka:
    client:
      fetch-registry: true
      register-with-eureka: true
      service-url:
        defaultZone: http://localhost:8761/eureka
logging:
  pattern:
    level: 5p [${spring.application.name}, %X{traceId:-}, %X{spanId:-}]

management:
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans
  tracing:
    sampling:
      probability: 1.0